apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibench-large
  labels:
    app: ibench-large
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibench-large
  template:
    metadata:
      labels:
        app: ibench-large
    spec:
      containers:
      - name: ibench-cpu
        image: stav1212/ibench:latest
        command: ["./cpu"]
        args: ["7200"]
        resources:
          requests:
            cpu: "1800m"     
            memory: "256Mi"
          limits:
            cpu: "1800m"     
            memory: "256Mi"  
