apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibench-medium
  labels:
    app: ibench-medium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibench-medium
  template:
    metadata:
      labels:
        app: ibench-medium
    spec:
      containers:
      - name: ibench-cpu
        image: stav1212/ibench:latest
        command: ["./cpu"]
        args: ["7200"]
        resources:
          requests:
            cpu: "1500m"   
            memory: "256Mi"
          limits:
            cpu: "1500m"     
            memory: "256Mi"  
