apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-processing-kata
  labels:
    app: image-processing-kata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-processing-kata
  template:
    metadata:
      labels:
        app: image-processing-kata
    spec:
      runtimeClassName: kata-fc
      containers:
      - name: image-processing
        image: stav1212/image_processing:v2
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "1536Mi"
            cpu: "1500m"

---
apiVersion: v1
kind: Service
metadata:
  name: image-processing-kata-service
spec:
  selector:
    app: image-processing-kata
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort
