apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: image-processing-kata
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: image-processing-kata  # ← Targets kata service
  endpoints:
  - interval: 30s
    port: web
    path: /metrics
